name: Token Lending Pull Request

on:
  pull_request:
    paths:
    - 'token-lending/**'
    - 'token/**'
  push:
    branches: [master]
    paths:
    - 'token-lending/**'
    - 'token/**'

jobs:
  cargo-test-bpf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2

      - name: Set env vars
        run: |
          source ci/rust-version.sh
          echo "RUST_STABLE=$rust_stable" >> $GITHUB_ENV
          source ci/solana-version.sh
          echo "SOLANA_VERSION=$solana_version" >> $GITHUB_ENV

      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1
        with:
          toolchain: ${{ env.RUST_STABLE }}
          override: true
          profile: minimal

      - uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-build-${{ hashFiles('**/Cargo.lock') }}-${{ env.RUST_STABLE}}

      - uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        with:
          path: |
            ~/.cargo/bin/rustfilt
          key: cargo-bpf-bins-${{ runner.os }}

      - uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        with:
          path: |
            ~/.cache
          key: solana-${{ env.SOLANA_VERSION }}

      - name: Install dependencies
        run: |
          ./ci/install-build-deps.sh
          ./ci/install-program-deps.sh
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Build and test
        run: ./ci/cargo-test-bpf.sh token-lending

      - name: Upload programs
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2
        with:
          name: token-lending-programs
          path: "target/deploy/*.so"
          if-no-files-found: error
