name: Pull Request

on:
  pull_request:
    paths-ignore:
    - 'docs/**'
  push:
    branches: [master, upcoming]
    paths-ignore:
    - 'docs/**'

jobs:
  all_github_action_checks:
    runs-on: ubuntu-latest
    needs:
      - rustfmt
      - clippy
      - cargo-build-test
    steps:
      - run: echo "Done"

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2

      - name: Set env vars
        run: |
          source ci/rust-version.sh
          echo "RUST_STABLE=$rust_stable" >> $GITHUB_ENV

      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1
        with:
          toolchain: ${{ env.RUST_STABLE }}
          override: true
          profile: minimal
          components: rustfmt

      - name: Run fmt
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2

      - name: Set env vars
        run: |
          source ci/rust-version.sh
          echo "RUST_NIGHTLY=$rust_nightly" >> $GITHUB_ENV

      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1
        with:
          toolchain: ${{ env.RUST_NIGHTLY }}
          override: true
          profile: minimal
          components: clippy

      - uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-clippy-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-clippy-

      - name: Install dependencies
        run: ./ci/install-build-deps.sh

      - name: Run clippy
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1
        with:
          command: clippy
          args: -Zunstable-options --workspace --all-targets -- --deny=warnings

  cargo-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2

      - name: Set env vars
        run: |
          source ci/rust-version.sh
          echo "RUST_STABLE=$rust_stable" >> $GITHUB_ENV
          source ci/solana-version.sh
          echo "SOLANA_VERSION=$solana_version" >> $GITHUB_ENV

      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1
        with:
          toolchain: ${{ env.RUST_STABLE }}
          override: true
          profile: minimal

      - uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            # target # Removed due to build dependency caching conflicts
          key: cargo-build-${{ hashFiles('**/Cargo.lock') }}-${{ env.RUST_STABLE}}

      - uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        with:
          path: |
            ~/.cargo/bin/rustfilt
          key: cargo-bpf-bins-${{ runner.os }}

      - uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        with:
          path: |
            ~/.cache
          key: solana-${{ env.SOLANA_VERSION }}

      - name: Install dependencies
        run: |
          ./ci/install-build-deps.sh
          ./ci/install-program-deps.sh
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Build and test
        run: ./ci/cargo-build-test.sh

  cargo-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2

      - name: Set env vars
        run: |
          source ci/rust-version.sh nightly
          echo "RUST_NIGHTLY=$rust_nightly" >> $GITHUB_ENV
          source ci/solana-version.sh
          echo "SOLANA_VERSION=$solana_version" >> $GITHUB_ENV

      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1
        with:
          toolchain: ${{ env.RUST_NIGHTLY }}
          override: true
          profile: minimal

      - uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            # target # Removed due to build dependency caching conflicts
          key: cargo-build-${{ hashFiles('**/Cargo.lock') }}-${{ env.RUST_NIGHTLY }}

      - name: Install dependencies
        run: |
          ./ci/install-build-deps.sh
          ./ci/install-program-deps.sh
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: run test coverage
        run: ./coverage.sh token-lending

      - name: Codecov
        uses: codecov/codecov-action@81cd2dc8148241f03f5839d295e000b8f761e378 # v3.1.0
        with:
          file: target/cov/cobertura.xml
